default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: rw
  password: hzckuvK6rqDrvEy6gcP

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test
